version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
    - .env
    ports:
      - "9090:80"